title: NVTC Data Analytics Documentation
description: A repository with a GitHub Pages deployment of NVTC's documentation
theme: just-the-docs

color_scheme: nova

url: https://novatransit.github.io

