title: NVTC Documentation
description: A repository with a GitHub Pages deployment of NVTC's data analysis documentation
theme: just-the-docs

color_scheme: green

logo: "https://novatransit.org/wp-content/uploads/NVTC-logo-retina@2x.png"

url: https://novatransit.github.io

aux_links:
  NVTC website:
    - https://novatransit.org